### ISSUE TITLE
error in compiling the matrixOperation.cpp , please check the code if its correct

### ISSUE THREAD

**Issue by anikde** [anikde/Combined-project#3]
![Screenshot from 2019-06-11 13-56-37](https://user-images.githubusercontent.com/30068060/59265094-48593400-8c62-11e9-8877-af20057e6619.png)

**Comment by deysumitkr** [comment]
Please, edit your post to include the errors as well. 
It will be better if you can copy-paste the errors instead of screenshot.

**Comment by anikde** [comment]
I have declared  function matrixScalerMultiplication()  in matrixOperation.h  thinking it might work that way considering the  return type to be void.
I tried to do it in a very simple way still there is some error in myMain.cpp.  
I have inserted screenshots of updated file of  myMain.cpp ; matrixOperations.h ; matrixOperations.cpp  & Error 
![image](https://app.gitkraken.com/api/glo/boards/5cced828dff7ab000f2102aa/attachments/5d012a8385316f000fa4274f)
![image](https://app.gitkraken.com/api/glo/boards/5cced828dff7ab000f2102aa/attachments/5d012a8bb042e2000faf6f68)
![image](https://app.gitkraken.com/api/glo/boards/5cced828dff7ab000f2102aa/attachments/5d012a94b21c58000ff8fc38)
![image](https://app.gitkraken.com/api/glo/boards/5cced828dff7ab000f2102aa/attachments/5d012aa185316f000fa42757)

Error Shown in terminal is :
anikde@anikde-Lenovo-Z50-70:~/Documents/gittest/Combined-project/build$ cmake ..
Value of EXE_NAME is: SimpleCodes-bin
Lets see what is the value of PROJECT_SOURCE_DIR -> /home/anikde/Documents/gittest/Combined-project
-- Configuring done
-- Generating done
-- Build files have been written to: /home/anikde/Documents/gittest/Combined-project/build
anikde@anikde-Lenovo-Z50-70:~/Documents/gittest/Combined-project/build$ make
[ 40%] Built target matrixOperations
[ 60%] Building CXX object CMakeFiles/SimpleCodes-bin.dir/myMain.cpp.o
/home/anikde/Documents/gittest/Combined-project/myMain.cpp: In function ‘int main(int, char**)’:
/home/anikde/Documents/gittest/Combined-project/myMain.cpp:57:36: error: variable or field ‘matrixScalerMultiplier’ declared void
         void matrixScalerMultiplier( 3, 3, 2, &array);
                                    ^
CMakeFiles/SimpleCodes-bin.dir/build.make:62: recipe for target 'CMakeFiles/SimpleCodes-bin.dir/myMain.cpp.o' failed
make[2]: *** [CMakeFiles/SimpleCodes-bin.dir/myMain.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/SimpleCodes-bin.dir/all' failed
make[1]: *** [CMakeFiles/SimpleCodes-bin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
anikde@anikde-Lenovo-Z50-70:~/Documents/gittest/Combined-project/build$

**Comment by deysumitkr** [comment]
`main.cpp` line 57:
`void matrixScalerMultiplier( 3, 3, 2, &array);`

You have mixed function declaration and a function call into one - resulting in invalid syntax.
I presume that you wish to call the function and not declare it. This function can be called by
`matrixScalerMultiplier( 3, 3, 2, &array);`.
Function calls do not mention return types like `void`, `int` etc. 

Return type of function is mentioned during declaration and definition; but is not mentioned for a function call. Read here: [functions - declaration, definition, call](https://www.tutorialspoint.com/cprogramming/c_functions.htm)  

PS
`&array` doesn't look right either!

**Comment by anikde** [comment]
This issue was resolve successfully and now i am to build the program.
